In [1]:
ll = [1,]
for i  in ll:
    print(i)

1

In [2]:
from __future__ import print_function
__file__ = !cd .. ;pwd
__file__ = __file__[0]
__file__

'/Users/brucecottman/Documents/PROJECTS/paso'

In [3]:
import sys
from random import random
import pandas as pd
from pandas_summary import DataFrameSummary

sys.path.append(__file__)
sys.path

['/Users/brucecottman/Documents/PROJECTS/paso/lessons',
 '/Users/brucecottman/anaconda3/envs/paso/lib/python37.zip',
 '/Users/brucecottman/anaconda3/envs/paso/lib/python3.7',
 '/Users/brucecottman/anaconda3/envs/paso/lib/python3.7/lib-dynload',
 '',
 '/Users/brucecottman/.local/lib/python3.7/site-packages',
 '/Users/brucecottman/anaconda3/envs/paso/lib/python3.7/site-packages',
 '/Users/brucecottman/anaconda3/envs/paso/lib/python3.7/site-packages/aeosa',
 '/Users/brucecottman/anaconda3/envs/paso/lib/python3.7/site-packages/IPython/extensions',
 '/Users/brucecottman/.ipython',
 '/Users/brucecottman/Documents/PROJECTS/paso']

In [4]:
from paso.pre.inputers import Inputer,Splitter
inputer = Inputer()
inputer.inputers()
inputer.transform(ontological_filepath='../ontologies/pre/inputers/iris.yaml')
Flower=inputer.train
type(Flower)

2019-07-25 13:00:29.640 | INFO     | paso.base:wrapper:264 - Loaded Ontological file:../ontologies/pre/inputers/iris.yaml

pandas.core.frame.DataFrame

In [5]:
inputer_b = Inputer()
Wine = inputer_b.transform(ontological_filepath='../ontologies/pre/inputers/wine.yaml')

2019-07-25 13:00:29.676 | INFO     | paso.base:wrapper:264 - Loaded Ontological file:../ontologies/pre/inputers/wine.yaml

In [6]:
DataFrameSummary(Wine).summary()

,Class,Alcohol,Malic-acid,Ash,Alcalinity-ash,Magnesium,phenols,Flavanoids,Nonflavanoid-phenols,Proanthocyanins,Color-intensity,Hue,OD280-OD315-diluted-wines,Proline
count,178,178,178,178,178,178,178,178,178,178,178,178,178,178
mean,1.9382,13.0006,2.33635,2.36652,19.4949,99.7416,2.29511,2.02927,0.361854,1.5909,5.05809,0.957449,2.61169,746.893
std,0.775035,0.811827,1.11715,0.274344,3.33956,14.2825,0.625851,0.998859,0.124453,0.572359,2.31829,0.228572,0.70999,314.907
min,1,11.03,0.74,1.36,10.6,70,0.98,0.34,0.13,0.41,1.28,0.48,1.27,278
25%,1,12.3625,1.6025,2.21,17.2,88,1.7425,1.205,0.27,1.25,3.22,0.7825,1.9375,500.5
50%,2,13.05,1.865,2.36,19.5,98,2.355,2.135,0.34,1.555,4.69,0.965,2.78,673.5
75%,3,13.6775,3.0825,2.5575,21.5,107,2.8,2.875,0.4375,1.95,6.2,1.12,3.17,985
max,3,14.83,5.8,3.23,30,162,3.88,5.08,0.66,3.58,13,1.71,4,1680
counts,178,178,178,178,178,178,178,178,178,178,178,178,178,178
uniques,3,126,133,79,63,53,97,132,39,101,132,78,122,121
missing,0,0,0,0,0,0,0,0,0,0,0,0,0,0
missing_perc,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%,0%
types,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric

In [7]:
splitter = Splitter()
train,valid=splitter.transform(Flower,target=inputer.target,ontological_filepath='../ontologies/pre/inputers/split-stratify-shuffle-20.yaml')

2019-07-25 13:00:30.365 | INFO     | paso.base:wrapper:264 - Loaded Ontological file:../ontologies/pre/inputers/split-stratify-shuffle-20.yaml

In [13]:
DataFrameSummary(splitter.X_test).summary()

,petal length (cm),petal width (cm),sepal length (cm),sepal width (cm),TypeOf
count,30,30,30,30,30
mean,3.83333,1.18333,5.91333,2.99667,1
std,1.91839,0.783046,1.00507,0.396957,0.830455
min,1,0.1,4.4,2.2,0
25%,1.625,0.225,5.1,2.8,0
50%,4.2,1.3,5.75,3,1
75%,5.25,1.9,6.625,3.175,2
max,6.9,2.4,7.7,4.1,2
counts,30,30,30,30,30
uniques,23,14,20,14,3
missing,0,0,0,0,0
missing_perc,0%,0%,0%,0%,0%
types,numeric,numeric,numeric,numeric,numeric